import manifest from "@/lib/cv-pages.json";

// The CV viewer: pre-rendered images of public/files/cv.pdf, shown as paper
// sheets in the site's own design. The images are generated by
// scripts/build-cv-pages.py whenever the CV is updated, and
// scripts/check-cv-pages.mjs fails the build if they ever lag behind the PDF,
// so what this shows is always exactly the published CV. Rendered at 2x the
// 860px display width, so pages stay sharp on retina screens and phone zoom.
export function CvPages() {
  const total = manifest.pages.length;
  return (
    <div className="cv-pages">
      {manifest.pages.map((page, i) => (
        <figure
          key={page.file}
          className="cv-page enter"
          style={{ "--enter-i": i + 2 } as React.CSSProperties}
        >
          <img
            src={`/images/cv-pages/${page.file}`}
            width={page.width}
            height={page.height}
            alt={`Curriculum Vitae, page ${i + 1} of ${total}`}
            loading={i === 0 ? "eager" : "lazy"}
            fetchPriority={i === 0 ? "high" : "auto"}
            decoding="async"
          />
        </figure>
      ))}
    </div>
  );
}
